# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Angry Chaired web: https://angrychaired.surge.sh
  Github profile: https://github.com/ikaem/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'daily'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /angry-chaired-blog/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: